apiVersion: apps/v1
kind: Deployment
metadata:
  name: qqdert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qqdert
  template:
    metadata:
      labels:
        app: qqdert
    spec:
      containers:
      - image: okteto.dev/qqdert:latest
        name: qqdert
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "824ca9d4-60ae-474b-a192-e0293138a2f2"
        - name: Vless_Path
          value: "/vlanlyfhDER"
        - name: Vmess_UUID
          value: "824ca9d4-60ae-474b-a192-e0293138a2f2"
        - name: Vmess_Path
          value: "/vmEoawerh"
        - name: Share_Path
          value: "/v2link"
